biomarker_noise_scale: 5.0
chaos_intensity: 0.0
elderly_noise_scale: 6.0
enable_age_variance: false
enable_correlations: false
enable_heavy_tails: false
enable_interactions: false
enable_nonlinearity: false
exponential_features: true
interaction_strength: 1.0
levy_alpha: 1.5
levy_scale: 5.0
lifestyle_correlation: 0.3
logarithmic_features: true
methylation_correlation: 0.35
middle_noise_scale: 4.0
n_second_order: 60
n_third_order: 20
pathway_correlation: 0.4
polynomial_degree: 2
random_seed: 42
student_t_df: 3
threshold_effects: true
young_noise_scale: 2.0
